name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Check package version matches release
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          RELEASE_VERSION=${{ github.event.release.tag_name }}
          if [[ "v$PKG_VERSION" != "$RELEASE_VERSION" ]]; then exit 1; fi
      - name: Install dependencies, build, lint, and test
        run: |
          npm ci
          npm run build
          npm run lint
          npm run test
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
