name: Run Tests
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies, build, lint, and test
        run: |
          npm ci
          npm run build
          npm run lint
          npm run test
